[package]
name = "chess-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "chess-cli"
path = "src/cli.rs"

[[bin]]
name = "chess-gui"
path = "src/gui.rs"

[dependencies]
chess-core = { path = "../chess-core" }
chess-engine = { path = "../chess-engine" }

chess = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }

eframe = { workspace = true }
egui = { workspace = true }
env_logger = { workspace = true }

[lints]
workspace = true
